### ISSUE TITLE
Some game states not saved upon completing battle

### ISSUE THREAD

**Issue by j-ackyao** [anjx123/Wastelanders#89]
### Description
It seems the only times in which the game state is saved via the persistence library is when the `CombatManager.Instance.GameState` gets changed by the fight scenes/dialogue, which then subsequently evoke `CombatManager`'s `PerformWin()` method to saving the game state. However, there are states that are set *after* the game win (e.g. post battle dialogues), which may not be saved correctly or at all, since the next save may not be evoked to reflect these changes.

### Proposal
Explicitly evoke these saves using the persistence interface OR evoke saves upon scene changes.

**Comment by anjx123** [comment]
Closed with MR # 97
